# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import minitwitter_pb2 as minitwitter__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in minitwitter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MiniTwitterStub(object):
    """Define the service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendMessage = channel.unary_unary(
                '/minitwitter.MiniTwitter/sendMessage',
                request_serializer=minitwitter__pb2.MessageRequest.SerializeToString,
                response_deserializer=minitwitter__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.getMessages = channel.unary_unary(
                '/minitwitter.MiniTwitter/getMessages',
                request_serializer=minitwitter__pb2.MessageListRequest.SerializeToString,
                response_deserializer=minitwitter__pb2.MessageListResponse.FromString,
                _registered_method=True)


class MiniTwitterServicer(object):
    """Define the service
    """

    def sendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MiniTwitterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.sendMessage,
                    request_deserializer=minitwitter__pb2.MessageRequest.FromString,
                    response_serializer=minitwitter__pb2.MessageResponse.SerializeToString,
            ),
            'getMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.getMessages,
                    request_deserializer=minitwitter__pb2.MessageListRequest.FromString,
                    response_serializer=minitwitter__pb2.MessageListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minitwitter.MiniTwitter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('minitwitter.MiniTwitter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MiniTwitter(object):
    """Define the service
    """

    @staticmethod
    def sendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minitwitter.MiniTwitter/sendMessage',
            minitwitter__pb2.MessageRequest.SerializeToString,
            minitwitter__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minitwitter.MiniTwitter/getMessages',
            minitwitter__pb2.MessageListRequest.SerializeToString,
            minitwitter__pb2.MessageListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
