# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: minitwitter.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'minitwitter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11minitwitter.proto\x12\x0bminitwitter\"!\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0fMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"#\n\x12MessageListRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"7\n\x13MessageListResponse\x12\x10\n\x08messages\x18\x01 \x03(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\xa9\x01\n\x0bMiniTwitter\x12H\n\x0bsendMessage\x12\x1b.minitwitter.MessageRequest\x1a\x1c.minitwitter.MessageResponse\x12P\n\x0bgetMessages\x12\x1f.minitwitter.MessageListRequest\x1a .minitwitter.MessageListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'minitwitter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=34
  _globals['_MESSAGEREQUEST']._serialized_end=67
  _globals['_MESSAGERESPONSE']._serialized_start=69
  _globals['_MESSAGERESPONSE']._serialized_end=102
  _globals['_MESSAGELISTREQUEST']._serialized_start=104
  _globals['_MESSAGELISTREQUEST']._serialized_end=139
  _globals['_MESSAGELISTRESPONSE']._serialized_start=141
  _globals['_MESSAGELISTRESPONSE']._serialized_end=196
  _globals['_MINITWITTER']._serialized_start=199
  _globals['_MINITWITTER']._serialized_end=368
# @@protoc_insertion_point(module_scope)
